apiVersion: v1
kind: Service
metadata: 
  name: postgres-service
  labels: 
    name: postgres-service
    type: db
spec: 
  ports:
   - port: 5432
     targetPort: 5432
  selector:
    name: postgres-pod
    type: db