apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    type: db
spec:
  containers:
  - name: redis
    image: redis:latest
    ports:
      - containerPort: 6379