apiVersion: v1
kind: Pod
metadata:
  name: result-pod
  labels:
    name: result-pod
    type: front-end
spec:
  containers:
  - name: result-app
    image: dockersamples/examplevotingapp_result
    ports:
      - containerPort: 80
        