apiVersion: v1
kind: Pod
metadata:
  name: voting-pod
  labels:
    name: voting-pod
    type: front-end
spec:
  containers:
  - name: voting-app-image
    image: dockersamples/examplevotingapp_vote
    ports:
      - containerPort: 80
        