apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: worker-pod
    type: back-end
spec:
  containers:
  - name: worker-app
    image: dockersamples/examplevotingapp_worker
    
        